name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Nix
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          curl --proto '=https' --tlsv1.2 -L https://releases.nixos.org/nix/nix-2.35.2/install | sh -s -- --no-daemon
          export USER=$(whoami)
          . "$HOME/.nix-profile/etc/profile.d/nix.sh"
          echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH
          echo "NIX_SSL_CERT_FILE=$NIX_SSL_CERT_FILE" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Prepare ccache
        id: prepare_ccache
        run: |
          echo "timestamp=$(TZ=UTC date "+%Y-%m-%d-T%H:%M:%S")" >> $GITHUB_OUTPUT
          CCACHE_DIR=$GITHUB_WORKSPACE/.ccache
          echo "CCACHE_DIR=$GITHUB_WORKSPACE/.ccache" >> $GITHUB_ENV
          mkdir -p "$CCACHE_DIR"
          nixpkgs=$(nix-instantiate --eval -E 'with import nix/pins; "${nixpkgs}"' --read-write-mode --raw)
          echo "NIX_PATH=nixpkgs=$nixpkgs" >> $GITHUB_ENV
          echo 'NIX_CONFIG<<EOF' >> $GITHUB_ENV
          echo "extra-sandbox-paths = /var/ccache=$CCACHE_DIR" >> $GITHUB_ENV
          echo "max-jobs = auto" >> $GITHUB_ENV
          echo "sandbox-fallback = false" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Set up ccache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: .ccache
          key: ccache-${{ github.job }}-${{ steps.prepare_ccache.outputs.timestamp }}
          restore-keys: ccache-${{ github.job }}-
      - name: Build
        run: |
          nix-build -A riscv-isa-sim --log-format bar-with-logs --arg withCCache true
      - name: Show ccache statistics
        run: |
          nix-shell -p ccache --run "ccache -s"
          nix-shell -p ccache --run "ccache -z"
